#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/opt/google/gwt/gwt-linux-0.0.2030_M1/gwt-user.jar:/opt/google/gwt/gwt-linux-0.0.2030_M1/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.tribling.gwt.test.feedback.Feedback;
