#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/opt/gwt-linux-1.4.61/gwt-user.jar:/opt/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.tribling.gwt.test.calendar.Calendar;
