#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/opt/google/gwt/gwt-linux-1.5.1/gwt-user.jar:/opt/google/gwt/gwt-linux-1.5.1/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.tribling.gwt.sandbox.SandBox/SandBox.html;
