#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/opt/google/gwt/gwt-linux-0.0.2415_M2/gwt-user.jar:/opt/google/gwt/gwt-linux-0.0.2415_M2/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.tribling.gwt.test.richtexteditorpopup.RichTextEditorPopUp/RichTextEditorPopUp.html;
