function com_tribling_gwt_test_history_HistoryAnchor(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',Cb='"><\/script>',n='/',kb='1573CA7D1D85E55279004ABD71DC7824.cache.html',mb='56DA3A3A37B96E13B02637E3E4493EBC.cache.html',ib='634A73C39AB672C29C3D618082BC9E1F.cache.html',tb='<link rel="stylesheet" href="',Bb='<script id="',wb='<script language="javascript" src="',zb="<script>com_tribling_gwt_test_history_HistoryAnchor.onInjectionDone('com.tribling.gwt.test.history.HistoryAnchor')<\/script>",v='=',y='Bad handler "',lb='D87AF9F8ABFA9EACFAEEFD24A638EF6E.cache.html',jb='DEB489B57FDAF518620E6D030F49413F.cache.html',ob='DOMContentLoaded',Db='SCRIPT',Ab='__gwt_marker_com.tribling.gwt.test.history.HistoryAnchor',o='base',q='clear.cache.gif',m='com.tribling.gwt.test.history.HistoryAnchor',u='content',db='gecko',eb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',hb='hosted.html?com_tribling_gwt_test_history_HistoryAnchor',bb='ie6',pb='iframe',p='img',qb="javascript:''",r='meta',gb='moduleRequested',ab='msie',s='name',D='opera',rb='position:absolute;width:0;height:0;border:none',F='safari',yb='selectionDone',cb='selectionStart',x='startup',sb='style.css',ub='style.css">',fb='unknown',vb='urchin.js',xb='urchin.js"><\/script>',C='user.agent',E='webkit';var Fb=window,k=document,hc=Fb.external,Eb=Fb.__gwtstatsEvent?function(a,b,c,d){Fb.__gwtstatsEvent(a,b,c,d)}:null,uc,kc,ec,dc=l,nc={},xc=[],tc=[],cc=[],qc,sc;Eb&&Eb(m,x,cb,{millis:(new Date()).getTime()});if(!Fb.__gwt_stylesLoaded){Fb.__gwt_stylesLoaded={}}if(!Fb.__gwt_scriptsLoaded){Fb.__gwt_scriptsLoaded={}}function jc(){try{return hc&&(hc.gwtOnLoad&&Fb.location.search.indexOf(nb)==-1)}catch(a){return false}}
function mc(){if(uc&&kc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_tribling_gwt_test_history_HistoryAnchor.__gwt_initHandlers;if(jc()){b.__gwt_getProperty=function(a){return fc(a)}}com_tribling_gwt_test_history_HistoryAnchor=null;b.gwtOnLoad(qc,m,dc);Eb&&Eb(m,x,yb,{millis:(new Date()).getTime()})}}
function gc(){var j,h=Ab,i;k.write(Bb+h+Cb);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=Db){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){dc=d(j.src)}if(dc==l){var c=k.getElementsByTagName(o);if(c.length>0){dc=c[c.length-1].href}else{var g=k.location;var e=g.href;dc=d(e.substr(0,e.length-g.hash.length))}}else if(dc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=dc+q;dc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function rc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}nc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{sc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{qc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function wc(d,e){var a=cc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function fc(d){var e=tc[d](),b=xc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(sc){sc(d,a,e)}throw null}
tc[C]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(D)!=-1){return D}else if(d.indexOf(E)!=-1){return F}else if(d.indexOf(ab)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return bb}}}else if(d.indexOf(db)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return eb}return db}return fb};xc[C]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_tribling_gwt_test_history_HistoryAnchor.onInjectionDone=function(){uc=true;Eb&&Eb(m,x,gb,{millis:(new Date()).getTime()});mc()};com_tribling_gwt_test_history_HistoryAnchor.onScriptLoad=function(){kc=true;mc()};gc();rc();var vc;if(jc()){vc=hb}else{try{wc([D],ib);wc([db],jb);wc([eb],kb);wc([bb],lb);wc([F],mb);vc=cc[fc(C)]}catch(a){return}}var pc;function oc(){if(!ec){ec=true;mc();if(k.removeEventListener){k.removeEventListener(ob,oc,false)}if(pc){clearInterval(pc)}}}
var ic;function lc(){if(!ic){ic=true;var a=k.createElement(pb);a.src=qb;a.id=m;a.style.cssText=rb;a.tabIndex=-1;k.body.appendChild(a);a.src=dc+vc}}
if(k.addEventListener){k.addEventListener(ob,function(){lc();oc()},false)}var pc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){lc();oc()}},50);if(!__gwt_stylesLoaded[sb]){__gwt_stylesLoaded[sb]=true;document.write(tb+dc+ub)}if(!__gwt_scriptsLoaded[vb]){__gwt_scriptsLoaded[vb]=true;document.write(wb+dc+xb)}k.write(zb)}
com_tribling_gwt_test_history_HistoryAnchor.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};com_tribling_gwt_test_history_HistoryAnchor();